# Generated by Django 2.2 on 2019-06-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('equipe', models.CharField(max_length=255)),
                ('activated', models.BooleanField()),
            ],
        ),
    ]
