# Generated by Django 4.2.1 on 2023-05-31 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.eyuser'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='archiveData',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='eyuser',
            name='activated',
            field=models.CharField(default='checked', max_length=255),
        ),
        migrations.AlterField(
            model_name='eyuser',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='eyuser',
            name='equipe',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eyuser',
            name='password',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eyuser',
            name='role',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eyuser',
            name='type',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eyuser',
            name='userName',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
