# Generated by Django 4.2.1 on 2023-06-03 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eyuser',
            name='password',
        ),
        migrations.AddField(
            model_name='archive',
            name='equipe',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, to='user.equipe'),
        ),
        migrations.AddField(
            model_name='archive',
            name='progression',
            field=models.CharField(default='0%', max_length=255),
        ),
        migrations.AddField(
            model_name='archive',
            name='status',
            field=models.CharField(default='pending', max_length=255),
        ),
        migrations.AddField(
            model_name='archive',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, to='user.eyuser'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='equipeDesc',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='eyuser',
            name='access_token',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='eyuser',
            name='pwd',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='archive',
            name='archiveData',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='eyuser',
            name='activated',
            field=models.CharField(default='deactivated', max_length=255),
        ),
        migrations.AlterField(
            model_name='eyuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='eyuser',
            name='equipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user.equipe'),
        ),
        migrations.AlterField(
            model_name='eyuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='eyuser',
            name='role',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
