# Generated by Django 4.2.1 on 2023-06-02 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eyuser',
            old_name='password',
            new_name='access_token',
        ),
        migrations.AddField(
            model_name='archive',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.eyuser'),
        ),
        migrations.AddField(
            model_name='eyuser',
            name='pwd',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='archive',
            name='archiveData',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eyuser',
            name='activated',
            field=models.CharField(default='deactivated', max_length=255),
        ),
        migrations.AlterField(
            model_name='eyuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='eyuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eyuser',
            name='role',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
