# Generated by Django 3.2.12 on 2023-06-04 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='archiveData',
        ),
        migrations.RemoveField(
            model_name='eyuser',
            name='password',
        ),
        migrations.AddField(
            model_name='archive',
            name='dueDate',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='archive',
            name='equipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.equipe'),
        ),
        migrations.AddField(
            model_name='archive',
            name='file',
            field=models.FileField(default='', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='archive',
            name='progression',
            field=models.CharField(default='0%', max_length=255),
        ),
        migrations.AddField(
            model_name='archive',
            name='status',
            field=models.CharField(default='pending', max_length=255),
        ),
        migrations.AddField(
            model_name='equipe',
            name='project',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='eyuser',
            name='access_token',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='eyuser',
            name='pwd',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='archive',
            name='archiveName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='archive',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='eyuser',
            name='activated',
            field=models.CharField(default='deactivated', max_length=255),
        ),
        migrations.AlterField(
            model_name='eyuser',
            name='email',
            field=models.EmailField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='eyuser',
            name='equipe',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='eyuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='eyuser',
            name='role',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='eyuser',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
