# Generated by Django 3.2.12 on 2023-06-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20230604_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eyuser',
            name='email',
            field=models.EmailField(max_length=255, null=True, unique=True),
        ),
    ]
