# Generated by Django 3.2.12 on 2023-06-04 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_eyuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='equipe',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='user.equipe'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='user.eyuser'),
        ),
    ]
